@startuml
title ユースケース図
actor ユーザー
actor 管理者 
rectangle ECサイト{
ユーザー --> (買う)
ユーザー --> (出品)
ユーザー --> (お気に入り)
ユーザー --> (受取評価)
ユーザー --> (支払い)
ユーザー --> (ログイン)
管理者 --> (ユーザーの削除)
管理者 --> (投稿の削除)  
}
ユーザー -->(受け取り)
ユーザー -->(出品)

@enduml